package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int idActividad;
     private Serializable nombreActividad;
     private Date fechaActividad;
     private Serializable lugarActividad;
     private Serializable temasActividad;
     private int statusActividad;

    public Actividad() {
    }

    public Actividad(int idActividad, Serializable nombreActividad, Date fechaActividad, Serializable lugarActividad, Serializable temasActividad, int statusActividad) {
       this.idActividad = idActividad;
       this.nombreActividad = nombreActividad;
       this.fechaActividad = fechaActividad;
       this.lugarActividad = lugarActividad;
       this.temasActividad = temasActividad;
       this.statusActividad = statusActividad;
    }
   
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public Serializable getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(Serializable nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public Date getFechaActividad() {
        return this.fechaActividad;
    }
    
    public void setFechaActividad(Date fechaActividad) {
        this.fechaActividad = fechaActividad;
    }
    public Serializable getLugarActividad() {
        return this.lugarActividad;
    }
    
    public void setLugarActividad(Serializable lugarActividad) {
        this.lugarActividad = lugarActividad;
    }
    public Serializable getTemasActividad() {
        return this.temasActividad;
    }
    
    public void setTemasActividad(Serializable temasActividad) {
        this.temasActividad = temasActividad;
    }
    public int getStatusActividad() {
        return this.statusActividad;
    }
    
    public void setStatusActividad(int statusActividad) {
        this.statusActividad = statusActividad;
    }




}


