package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int idAdmin;
     private Serializable nombreAdmin;
     private Serializable codAdmin;

    public Admin() {
    }

	
    public Admin(int idAdmin, Serializable nombreAdmin) {
        this.idAdmin = idAdmin;
        this.nombreAdmin = nombreAdmin;
    }
    public Admin(int idAdmin, Serializable nombreAdmin, Serializable codAdmin) {
       this.idAdmin = idAdmin;
       this.nombreAdmin = nombreAdmin;
       this.codAdmin = codAdmin;
    }
   
    public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }
    public Serializable getNombreAdmin() {
        return this.nombreAdmin;
    }
    
    public void setNombreAdmin(Serializable nombreAdmin) {
        this.nombreAdmin = nombreAdmin;
    }
    public Serializable getCodAdmin() {
        return this.codAdmin;
    }
    
    public void setCodAdmin(Serializable codAdmin) {
        this.codAdmin = codAdmin;
    }




}


