package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idContacto;
     private String nombrePcontacto;
     private String nombreScontacto;
     private String apellidoPcontacto;
     private String apellidoMcontacto;
     private String mailContacto;
     private String telefonoFijoContacto;
     private String celularContacto;

    public Contacto() {
    }

	
    public Contacto(int idContacto, String nombrePcontacto, String apellidoPcontacto) {
        this.idContacto = idContacto;
        this.nombrePcontacto = nombrePcontacto;
        this.apellidoPcontacto = apellidoPcontacto;
    }
    public Contacto(int idContacto, String nombrePcontacto, String nombreScontacto, String apellidoPcontacto, String apellidoMcontacto, String mailContacto, String telefonoFijoContacto, String celularContacto) {
       this.idContacto = idContacto;
       this.nombrePcontacto = nombrePcontacto;
       this.nombreScontacto = nombreScontacto;
       this.apellidoPcontacto = apellidoPcontacto;
       this.apellidoMcontacto = apellidoMcontacto;
       this.mailContacto = mailContacto;
       this.telefonoFijoContacto = telefonoFijoContacto;
       this.celularContacto = celularContacto;
    }
   
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }
    public Serializable getNombrePcontacto() {
        return this.nombrePcontacto;
    }
    
    public void setNombrePcontacto(String nombrePcontacto) {
        this.nombrePcontacto = nombrePcontacto;
    }
    public Serializable getNombreScontacto() {
        return this.nombreScontacto;
    }
    
    public void setNombreScontacto(String nombreScontacto) {
        this.nombreScontacto = nombreScontacto;
    }
    public Serializable getApellidoPcontacto() {
        return this.apellidoPcontacto;
    }
    
    public void setApellidoPcontacto(String apellidoPcontacto) {
        this.apellidoPcontacto = apellidoPcontacto;
    }
    public Serializable getApellidoMcontacto() {
        return this.apellidoMcontacto;
    }
    
    public void setApellidoMcontacto(String apellidoMcontacto) {
        this.apellidoMcontacto = apellidoMcontacto;
    }
    public Serializable getMailContacto() {
        return this.mailContacto;
    }
    
    public void setMailContacto(String mailContacto) {
        this.mailContacto = mailContacto;
    }
    public Serializable getTelefonoFijoContacto() {
        return this.telefonoFijoContacto;
    }
    
    public void setTelefonoFijoContacto(String telefonoFijoContacto) {
        this.telefonoFijoContacto = telefonoFijoContacto;
    }
    public Serializable getCelularContacto() {
        return this.celularContacto;
    }
    
    public void setCelularContacto(String celularContacto) {
        this.celularContacto = celularContacto;
    }
}


