package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idContacto;
     private Serializable nombrePcontacto;
     private Serializable nombreScontacto;
     private Serializable apellidoPcontacto;
     private Serializable apellidoMcontacto;
     private Serializable mailContacto;
     private Serializable telefonoFijoContacto;
     private Serializable celularContacto;

    public Contacto() {
    }

	
    public Contacto(int idContacto, Serializable nombrePcontacto, Serializable apellidoPcontacto) {
        this.idContacto = idContacto;
        this.nombrePcontacto = nombrePcontacto;
        this.apellidoPcontacto = apellidoPcontacto;
    }
    public Contacto(int idContacto, Serializable nombrePcontacto, Serializable nombreScontacto, Serializable apellidoPcontacto, Serializable apellidoMcontacto, Serializable mailContacto, Serializable telefonoFijoContacto, Serializable celularContacto) {
       this.idContacto = idContacto;
       this.nombrePcontacto = nombrePcontacto;
       this.nombreScontacto = nombreScontacto;
       this.apellidoPcontacto = apellidoPcontacto;
       this.apellidoMcontacto = apellidoMcontacto;
       this.mailContacto = mailContacto;
       this.telefonoFijoContacto = telefonoFijoContacto;
       this.celularContacto = celularContacto;
    }
   
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }
    public Serializable getNombrePcontacto() {
        return this.nombrePcontacto;
    }
    
    public void setNombrePcontacto(Serializable nombrePcontacto) {
        this.nombrePcontacto = nombrePcontacto;
    }
    public Serializable getNombreScontacto() {
        return this.nombreScontacto;
    }
    
    public void setNombreScontacto(Serializable nombreScontacto) {
        this.nombreScontacto = nombreScontacto;
    }
    public Serializable getApellidoPcontacto() {
        return this.apellidoPcontacto;
    }
    
    public void setApellidoPcontacto(Serializable apellidoPcontacto) {
        this.apellidoPcontacto = apellidoPcontacto;
    }
    public Serializable getApellidoMcontacto() {
        return this.apellidoMcontacto;
    }
    
    public void setApellidoMcontacto(Serializable apellidoMcontacto) {
        this.apellidoMcontacto = apellidoMcontacto;
    }
    public Serializable getMailContacto() {
        return this.mailContacto;
    }
    
    public void setMailContacto(Serializable mailContacto) {
        this.mailContacto = mailContacto;
    }
    public Serializable getTelefonoFijoContacto() {
        return this.telefonoFijoContacto;
    }
    
    public void setTelefonoFijoContacto(Serializable telefonoFijoContacto) {
        this.telefonoFijoContacto = telefonoFijoContacto;
    }
    public Serializable getCelularContacto() {
        return this.celularContacto;
    }
    
    public void setCelularContacto(Serializable celularContacto) {
        this.celularContacto = celularContacto;
    }




}


