package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idEmpresa;
     private String nombreEmpresa;
     private int statusEmpresa;

    public Empresa() {
    }

    public Empresa(int idEmpresa, String nombreEmpresa, int statusEmpresa) {
       this.idEmpresa = idEmpresa;
       this.nombreEmpresa = nombreEmpresa;
       this.statusEmpresa = statusEmpresa;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Serializable getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public int getStatusEmpresa() {
        return this.statusEmpresa;
    }
    
    public void setStatusEmpresa(int statusEmpresa) {
        this.statusEmpresa = statusEmpresa;
    }




}


