package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int idMarca;
     private Serializable nombreMarca;
     private int statusMarca;

    public Marca() {
    }

    public Marca(int idMarca, Serializable nombreMarca, int statusMarca) {
       this.idMarca = idMarca;
       this.nombreMarca = nombreMarca;
       this.statusMarca = statusMarca;
    }
   
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }
    public Serializable getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(Serializable nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public int getStatusMarca() {
        return this.statusMarca;
    }
    
    public void setStatusMarca(int statusMarca) {
        this.statusMarca = statusMarca;
    }




}


