package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idRol;
     private Serializable nombreRol;
     private int statusRol;

    public Rol() {
    }

    public Rol(int idRol, Serializable nombreRol, int statusRol) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.statusRol = statusRol;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public Serializable getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(Serializable nombreRol) {
        this.nombreRol = nombreRol;
    }
    public int getStatusRol() {
        return this.statusRol;
    }
    
    public void setStatusRol(int statusRol) {
        this.statusRol = statusRol;
    }




}


