package entity;
// Generated 05-feb-2016 19:16:39 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SalesSp generated by hbm2java
 */
public class SalesSp  implements java.io.Serializable {


     private int idSalesSp;
     private String nombrePsalesSp;
     private String nombreSsalesSp;
     private String apellidoPsalesSp;
     private String apellidoMsalesSp;
     private int statusSalesSp;

    public SalesSp() {
    }

	
    public SalesSp(int idSalesSp, String nombrePsalesSp, String apellidoPsalesSp, int statusSalesSp) {
        this.idSalesSp = idSalesSp;
        this.nombrePsalesSp = nombrePsalesSp;
        this.apellidoPsalesSp = apellidoPsalesSp;
        this.statusSalesSp = statusSalesSp;
    }
    public SalesSp(int idSalesSp, String nombrePsalesSp, String nombreSsalesSp, String apellidoPsalesSp, String apellidoMsalesSp, int statusSalesSp) {
       this.idSalesSp = idSalesSp;
       this.nombrePsalesSp = nombrePsalesSp;
       this.nombreSsalesSp = nombreSsalesSp;
       this.apellidoPsalesSp = apellidoPsalesSp;
       this.apellidoMsalesSp = apellidoMsalesSp;
       this.statusSalesSp = statusSalesSp;
    }
   
    public int getIdSalesSp() {
        return this.idSalesSp;
    }
    
    public void setIdSalesSp(int idSalesSp) {
        this.idSalesSp = idSalesSp;
    }
    public Serializable getNombrePsalesSp() {
        return this.nombrePsalesSp;
    }
    
    public void setNombrePsalesSp(String nombrePsalesSp) {
        this.nombrePsalesSp = nombrePsalesSp;
    }
    public Serializable getNombreSsalesSp() {
        return this.nombreSsalesSp;
    }
    
    public void setNombreSsalesSp(String nombreSsalesSp) {
        this.nombreSsalesSp = nombreSsalesSp;
    }
    public Serializable getApellidoPsalesSp() {
        return this.apellidoPsalesSp;
    }
    
    public void setApellidoPsalesSp(String apellidoPsalesSp) {
        this.apellidoPsalesSp = apellidoPsalesSp;
    }
    public Serializable getApellidoMsalesSp() {
        return this.apellidoMsalesSp;
    }
    
    public void setApellidoMsalesSp(String apellidoMsalesSp) {
        this.apellidoMsalesSp = apellidoMsalesSp;
    }
    public int getStatusSalesSp() {
        return this.statusSalesSp;
    }
    
    public void setStatusSalesSp(int statusSalesSp) {
        this.statusSalesSp = statusSalesSp;
    }




}


